name: Deploy to server
on:
  workflow_run:
    workflows: ["Build and Push Docker Image to GHCR on Main"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ${{ secrets.SERVER_PATH }}
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/bjt-app:main
            docker pull ${{ vars.DOCKERHUB_USERNAME }}/bjt-api:main
            docker stop bjt-app || true
            docker rm bjt-app || true
            docker stop bjt-api || true
            docker rm bjt-api || true
            docker run -d --name bjt-app --env-file .env -p 8009:80 ${{ vars.DOCKERHUB_USERNAME }}/bjt-app:main
            docker run -d --name bjt-api --env-file .env -p 3001:3001 ${{ vars.DOCKERHUB_USERNAME }}/bjt-api:main
